// import localFont from "next/font/local";
import "./globals.css";
import { Kantumruy_Pro } from 'next/font/google'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const kantumruyPro = Kantumruy_Pro({ subsets: ['latin'] })


export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className={kantumruyPro.className}
      >
        {children}
      </body>
    </html>
  );
}
